# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_emailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="weekly_schedule",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
