# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_userprofile_weekly_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(choices=[("PUBLIC", "Public"), ("PATIENT", "Patient"), ("DOCTOR", "Doctor"), ("ADMIN", "Admin"), ("COUNTER", "Counter"), ("STAFF", "Staff")], default="PATIENT", max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="staff_type",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="salary",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
