# Generated by Django 5.2.16 on 2026-08-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_appointment_confirmation_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
