from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("api", "0010_backfill_patient_ids")]
    operations = [
        migrations.AddField(model_name="prescription", name="signature_sha256", field=models.CharField(blank=True, default="", max_length=64)),
        migrations.CreateModel(name="EmailDeliveryLog", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("template_name", models.CharField(max_length=80)), ("recipient_domains", models.JSONField(blank=True, default=list)), ("delivered", models.BooleanField(default=False)), ("error_type", models.CharField(blank=True, default="", max_length=120)), ("created_at", models.DateTimeField(auto_now_add=True))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="ConsentRecord", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("document_type", models.CharField(max_length=40)), ("document_version", models.CharField(max_length=20)), ("accepted_at", models.DateTimeField(auto_now_add=True)), ("ip_address", models.GenericIPAddressField(blank=True, null=True)), ("user_agent", models.CharField(blank=True, default="", max_length=300)), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="consent_records", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="AdminAuditLog", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("action", models.CharField(max_length=80)), ("target_type", models.CharField(blank=True, default="", max_length=80)), ("target_id", models.CharField(blank=True, default="", max_length=80)), ("summary", models.TextField(blank=True, default="")), ("metadata", models.JSONField(blank=True, default=dict)), ("ip_address", models.GenericIPAddressField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="admin_audit_events", to=settings.AUTH_USER_MODEL))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="DataDeletionRequest", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("reason", models.TextField(blank=True, default="")), ("status", models.CharField(choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected"), ("COMPLETED", "Completed")], default="PENDING", max_length=20)), ("review_notes", models.TextField(blank=True, default="")), ("requested_at", models.DateTimeField(auto_now_add=True)), ("reviewed_at", models.DateTimeField(blank=True, null=True)), ("patient", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="data_deletion_requests", to=settings.AUTH_USER_MODEL)), ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_data_deletion_requests", to=settings.AUTH_USER_MODEL))]),
        migrations.AddConstraint(model_name="consentrecord", constraint=models.UniqueConstraint(fields=("user", "document_type", "document_version"), name="unique_user_document_consent")),
    ]
