# Generated by Django 5.2.14 on 2026-09-17 12:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def release_duplicate_active_slots(apps, schema_editor):
    Appointment = apps.get_model('api', 'Appointment')
    active = Appointment.objects.exclude(status__in=['Cancelled', 'NoShow', 'Rescheduled']).order_by('doctor_id', 'date', 'time', 'created_at', 'id')
    seen = set()
    for appointment in active.iterator():
        key = (appointment.doctor_id, appointment.date, appointment.time)
        if key in seen:
            appointment.status = 'Rescheduled'
            appointment.save(update_fields=['status'])
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userprofile_avatar_data_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('consultation_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreeCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('date', models.DateField()),
                ('location', models.CharField(default='Bhaktivedanta Health Care Center', max_length=200)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the payroll month')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, default='', max_length=40)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('remarks', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month', 'employee_id'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='department',
            name='token_prefix',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='labregistration',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='labregistration',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='api.department'),
        ),
        migrations.AddField(
            model_name='labregistration',
            name='department_sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labregistration',
            name='is_free_camp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labregistration',
            name='native_place',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='labregistration',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counter_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labregistration',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='labregistration',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='labregistration',
            name='token_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='native_place',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Booked'), ('CheckedIn', 'Checked in'), ('InConsultation', 'In consultation'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('NoShow', 'Not attended'), ('Rescheduled', 'Rescheduled')], default='Upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='labregistration',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labregistration',
            name='fee',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.RunPython(release_duplicate_active_slots, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Cancelled', 'NoShow', 'Rescheduled']), _negated=True), fields=('doctor', 'date', 'time'), name='unique_active_doctor_slot'),
        ),
        migrations.AddConstraint(
            model_name='labregistration',
            constraint=models.UniqueConstraint(fields=('department', 'registration_date', 'department_sequence'), name='unique_daily_department_token'),
        ),
        migrations.AddField(
            model_name='campregistration',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='camp_registration', to='api.labregistration'),
        ),
        migrations.AddField(
            model_name='freecamp',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_free_camps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freecamp',
            name='departments',
            field=models.ManyToManyField(related_name='free_camps', to='api.department'),
        ),
        migrations.AddField(
            model_name='campregistration',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='api.freecamp'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_payroll_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.UniqueConstraint(fields=('employee', 'month'), name='unique_employee_payroll_month'),
        ),
    ]
