# Generated by Django 5.2.14 on 2026-09-17 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_campregistration_freecamp_payrollrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campregistration',
            name='receipt_print_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campregistration',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='camp_patient_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freecamp',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for registration'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=12),
        ),
        migrations.CreateModel(
            name='CampDepartmentRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=40)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.freecamp')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camp_rooms', to='api.department')),
            ],
            options={
                'ordering': ['department__name', 'room_number'],
            },
        ),
        migrations.AddField(
            model_name='campregistration',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='api.campdepartmentroom'),
        ),
        migrations.AddConstraint(
            model_name='campdepartmentroom',
            constraint=models.UniqueConstraint(fields=('camp', 'department', 'room_number'), name='unique_camp_department_room'),
        ),
    ]
