# Generated by Django 5.2.14 on 2026-09-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_campregistration_receipt_print_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecamp',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for registration'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12),
        ),
    ]
