# Generated by Django 5.2.14 on 2026-09-18 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_freecamp_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campregistration',
            name='room',
        ),
        migrations.DeleteModel(
            name='CampDepartmentRoom',
        ),
    ]
