'use client';
import React from 'react';
import { User } from '@/types';
import { deleteStaffAccount, listAllAccounts, setAccountActive } from '@/services/clinicService';
import { Search, Shield, Trash2 } from 'lucide-react';

export default function AdminProfiles({currentUserId}:{currentUserId:string}){
 const [rows,setRows]=React.useState<User[]>([]),[query,setQuery]=React.useState(''),[message,setMessage]=React.useState('');
 const load=React.useCallback(()=>listAllAccounts().then(setRows),[]);React.useEffect(()=>{load().catch(e=>setMessage(e.message));},[load]);
 const visible=rows.filter(x=>[x.name,x.email,x.role,x.patientId,x.department,x.specialty].some(v=>(v||'').toLowerCase().includes(query.toLowerCase())));
 const toggle=async(row:User)=>{try{await setAccountActive(row.id,!row.isActive);await load();setMessage(`${row.name}'s login was ${row.isActive===false?'enabled':'deactivated'}.`);}catch(e){setMessage(e instanceof Error?e.message:'Could not update account.');}};
 const remove=async(row:User)=>{if(!window.confirm(`CAUTION: Permanently delete ${row.name} (${row.email})?\n\nThis cannot be undone. Accounts connected to clinical records will be protected and must be deactivated instead.`))return;try{await deleteStaffAccount(row.id);await load();setMessage(`${row.name}'s account was permanently deleted.`);}catch(e){setMessage(e instanceof Error?e.message:'Could not delete account.');}};
 return <main className="max-w-7xl mx-auto px-4 py-10 space-y-6"><div><h1 className="text-3xl font-black flex items-center gap-3"><Shield className="text-sky-600"/>All Profiles</h1><p className="text-gray-500">Read clinic profiles and control login access. Clinical records are protected from destructive deletion.</p></div>{message&&<p className="bg-sky-50 text-sky-800 p-4 rounded-xl">{message}</p>}<div className="relative"><Search className="absolute left-4 top-3.5 text-gray-400" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, email, role, patient ID or department" className="w-full border rounded-xl py-3 pl-11 pr-4"/></div><div className="bg-white border rounded-3xl overflow-x-auto"><table className="w-full text-left"><thead className="bg-gray-50"><tr><th className="p-4">Profile</th><th className="p-4">Role</th><th className="p-4">Details</th><th className="p-4">Login</th><th className="p-4">Controls</th></tr></thead><tbody>{visible.map(row=><tr key={row.id} className="border-t"><td className="p-4"><b>{row.name}</b><p className="text-sm text-gray-500">{row.email}</p></td><td className="p-4 font-bold">{row.role}</td><td className="p-4 text-sm text-gray-600">{row.patientId||[row.qualification,row.specialty,row.department].filter(Boolean).join(' · ')||row.staffType||'—'}</td><td className="p-4"><span className={row.isActive===false?'text-red-700':'text-green-700'}>{row.isActive===false?'Deactivated':'Active'}</span></td><td className="p-4"><div className="flex gap-3"><button disabled={row.id===currentUserId} onClick={()=>toggle(row)} className="font-bold text-amber-700 disabled:opacity-40">{row.isActive===false?'Enable':'Deactivate'}</button><button disabled={row.id===currentUserId} onClick={()=>remove(row)} className="inline-flex items-center font-bold text-red-700 disabled:opacity-40"><Trash2 size={15} className="mr-1"/>Delete</button></div></td></tr>)}</tbody></table>{!visible.length&&<p className="p-6 text-gray-500">No profiles found.</p>}</div></main>;
}
