'use client';
import React from 'react';
import { Department, FreeCamp } from '@/types';
import { createCampRoom, createFreeCamp, listDepartments, listFreeCamps, updateCampRoom, updateFreeCamp } from '@/services/clinicService';

export default function AdminCamps(){
 const [departments,setDepartments]=React.useState<Department[]>([]); const [camps,setCamps]=React.useState<FreeCamp[]>([]); const [message,setMessage]=React.useState('');
 const [form,setForm]=React.useState({name:'',date:'',location:'Bhaktivedanta Health Care Center',capacity:''});
 const [roomForm,setRoomForm]=React.useState({campId:'',departmentId:'',roomNumber:'',capacity:''});
 const load=()=>Promise.all([listDepartments(),listFreeCamps()]).then(([d,c])=>{setDepartments(d);setCamps(c)});
 React.useEffect(()=>{load().catch(()=>setMessage('Unable to load camps.'));},[]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();try{await createFreeCamp({...form,capacity:form.capacity?Number(form.capacity):undefined,departmentIds:[]});await load();setForm({name:'',date:'',location:'Bhaktivedanta Health Care Center',capacity:''});setMessage('Camp created. Add rooms and open registration.');}catch(error:any){setMessage(error?.message||'Could not create camp.')}};
 const addRoom=async(e:React.FormEvent)=>{e.preventDefault();try{await createCampRoom(roomForm.campId,{departmentId:roomForm.departmentId,roomNumber:roomForm.roomNumber,capacity:roomForm.capacity?Number(roomForm.capacity):undefined});await load();setRoomForm({...roomForm,departmentId:'',roomNumber:'',capacity:''});setMessage('Room mapped successfully.');}catch(error:any){setMessage(error?.message||'Could not map room.')}};
 const setStatus=async(camp:FreeCamp,status:FreeCamp['status'])=>{await updateFreeCamp(camp.id,{status});await load();};
 const changeRoomCapacity=async(room:FreeCamp['rooms'][number])=>{const answer=window.prompt(`Capacity for Room ${room.roomNumber}. Leave empty for unlimited patients.`,room.capacity?String(room.capacity):'');if(answer===null)return;const capacity=answer.trim()===''?null:Number(answer);if(capacity!==null&&(!Number.isInteger(capacity)||capacity<room.registrationCount)){setMessage(`Capacity must be at least the current ${room.registrationCount} registrations.`);return;}try{await updateCampRoom(room.id,{capacity});await load();setMessage(capacity===null?'Room capacity is now unlimited.':`Room capacity updated to ${capacity}.`);}catch(error:any){setMessage(error?.message||'Could not update room capacity.')}};
 return <div className="mx-auto max-w-7xl px-4 py-12"><h1 className="text-3xl font-black">Camp Management</h1><p className="mb-8 text-gray-500">Create camps, map multiple department rooms, and adjust room capacity as queues grow.</p>{message&&<p className="mb-5 rounded-xl bg-sky-50 p-3 text-sky-800">{message}</p>}
 <div className="grid gap-8 lg:grid-cols-2"><form onSubmit={submit} className="space-y-4 rounded-3xl border bg-white p-7"><h2 className="text-xl font-bold">1. Create camp</h2><input required placeholder="Camp name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="w-full rounded-xl border p-3"/><input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className="w-full rounded-xl border p-3"/><input required placeholder="Location" value={form.location} onChange={e=>setForm({...form,location:e.target.value})} className="w-full rounded-xl border p-3"/><input type="number" min="1" placeholder="Total camp capacity (optional)" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})} className="w-full rounded-xl border p-3"/><button className="w-full rounded-xl bg-sky-600 py-3 font-bold text-white">Create camp</button></form>
 <form onSubmit={addRoom} className="space-y-4 rounded-3xl border bg-white p-7"><h2 className="text-xl font-bold">2. Add another department room</h2><select required value={roomForm.campId} onChange={e=>setRoomForm({...roomForm,campId:e.target.value})} className="w-full rounded-xl border p-3"><option value="">Select camp</option>{camps.filter(c=>!['CLOSED','CANCELLED'].includes(c.status)).map(c=><option key={c.id} value={c.id}>{c.name} — {c.date}</option>)}</select><select required value={roomForm.departmentId} onChange={e=>setRoomForm({...roomForm,departmentId:e.target.value})} className="w-full rounded-xl border p-3"><option value="">Select department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><input required placeholder="Room number or name" value={roomForm.roomNumber} onChange={e=>setRoomForm({...roomForm,roomNumber:e.target.value})} className="w-full rounded-xl border p-3"/><input type="number" min="1" placeholder="Capacity (empty means unlimited)" value={roomForm.capacity} onChange={e=>setRoomForm({...roomForm,capacity:e.target.value})} className="w-full rounded-xl border p-3"/><button className="w-full rounded-xl bg-slate-900 py-3 font-bold text-white">Add room</button></form></div>
 <div className="mt-8 space-y-4">{camps.map(c=><article key={c.id} className="rounded-3xl border bg-white p-6"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-xl font-bold">{c.name}</h2><p className="text-gray-500">{c.date} · {c.location} · {c.status}</p><p className="text-sm">{c.registrationCount}{c.capacity?` / ${c.capacity}`:''} registrations</p></div><div className="flex gap-2">{c.status!=='OPEN'&&<button onClick={()=>setStatus(c,'OPEN')} className="rounded-lg bg-green-600 px-3 py-2 text-sm font-bold text-white">Open</button>}{c.status!=='CLOSED'&&<button onClick={()=>setStatus(c,'CLOSED')} className="rounded-lg border px-3 py-2 text-sm font-bold">Close</button>}{c.status!=='CANCELLED'&&<button onClick={()=>setStatus(c,'CANCELLED')} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-bold text-red-700">Cancel</button>}</div></div><div className="mt-4 grid gap-2 md:grid-cols-2">{c.rooms.map(room=><div key={room.id} className="flex items-center justify-between gap-3 rounded-xl bg-gray-50 p-3"><span><b>{room.departmentName}</b> — Room {room.roomNumber}<small className="block text-gray-500">{room.registrationCount}{room.capacity?` / ${room.capacity}`:' / unlimited'} patients</small></span><div className="flex gap-2"><button onClick={()=>changeRoomCapacity(room)} className="text-sm font-bold text-sky-700">Capacity</button><button onClick={async()=>{await updateCampRoom(room.id,{isActive:!room.isActive});await load();}} className="text-sm font-bold text-sky-700">{room.isActive?'Close':'Reopen'}</button></div></div>)}{c.rooms.length===0&&<p className="text-sm text-amber-700">No rooms configured.</p>}</div></article>)}</div></div>;
}
