'use client';

import React from 'react';
import { User } from '@/types';
import { deleteStaffAccount, listAllAccounts, purgeTestAccount, resetAccountPassword, setAccountActive } from '@/services/clinicService';
import { KeyRound, Search, Shield, Trash2 } from 'lucide-react';

export default function AdminProfiles({ currentUserId }: { currentUserId: string }) {
  const [rows, setRows] = React.useState<User[]>([]);
  const [query, setQuery] = React.useState('');
  const [message, setMessage] = React.useState('');
  const load = React.useCallback(() => listAllAccounts().then(setRows), []);
  React.useEffect(() => { load().catch((error) => setMessage(error.message)); }, [load]);

  const visible = rows.filter((row) => [row.name, row.email, row.role, row.patientId, row.department, row.specialty].some((value) => (value || '').toLowerCase().includes(query.toLowerCase())));
  const toggle = async (row: User) => { try { await setAccountActive(row.id, !row.isActive); await load(); setMessage(`${row.name}'s login was ${row.isActive === false ? 'enabled' : 'deactivated'}.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not update account.'); } };
  const remove = async (row: User) => { if (!window.confirm(`CAUTION: Permanently delete ${row.name} (${row.email})?\n\nAccounts connected to clinical records remain protected.`)) return; try { await deleteStaffAccount(row.id); await load(); setMessage(`${row.name}'s account was permanently deleted.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not delete account.'); } };
  const resetPassword = async (row: User) => { const password = window.prompt(`Enter a new temporary password for ${row.name}. The account will also be reactivated.`); if (!password) return; const confirmation = window.prompt('Enter the same temporary password again.'); if (password !== confirmation) { setMessage('The passwords did not match. Nothing was changed.'); return; } try { await resetAccountPassword(row.id, password); await load(); setMessage(`${row.name}'s password was reset and the account was reactivated.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not reset password.'); } };
  const purge = async (row: User) => { const expected = `DELETE ${row.email}`; const confirmation = window.prompt(`DANGER: Only use this for dummy/test accounts. This permanently deletes the account and every linked appointment, consultation and prescription.\n\nType exactly: ${expected}`); if (confirmation !== expected) { if (confirmation !== null) setMessage('Confirmation did not match. Nothing was deleted.'); return; } try { await purgeTestAccount(row.id, confirmation); await load(); setMessage(`${row.name}'s test account and linked clinical records were permanently deleted.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not purge test account.'); } };

  return <main className="max-w-7xl mx-auto px-4 py-10 space-y-6">
    <div><h1 className="text-3xl font-black flex items-center gap-3"><Shield className="text-sky-600" />All Profiles</h1><p className="text-gray-500">Manage login access and passwords. Clinical history remains protected unless you explicitly purge a dummy account.</p></div>
    {message && <p className="bg-sky-50 text-sky-800 p-4 rounded-xl">{message}</p>}
    <div className="relative"><Search className="absolute left-4 top-3.5 text-gray-400" size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, email, role, patient ID or department" className="w-full border rounded-xl py-3 pl-11 pr-4" /></div>
    <div className="bg-white border rounded-3xl overflow-x-auto"><table className="w-full text-left"><thead className="bg-gray-50"><tr><th className="p-4">Profile</th><th className="p-4">Role</th><th className="p-4">Details</th><th className="p-4">Login</th><th className="p-4">Controls</th></tr></thead><tbody>{visible.map((row) => <tr key={row.id} className="border-t"><td className="p-4"><b>{row.name}</b><p className="text-sm text-gray-500">{row.email}</p></td><td className="p-4 font-bold">{row.role}</td><td className="p-4 text-sm text-gray-600">{row.patientId || [row.qualification, row.specialty, row.department].filter(Boolean).join(' · ') || row.staffType || '—'}</td><td className="p-4"><span className={row.isActive === false ? 'text-red-700' : 'text-green-700'}>{row.isActive === false ? 'Deactivated' : 'Active'}</span></td><td className="p-4"><div className="flex flex-wrap gap-3"><button disabled={row.id === currentUserId} onClick={() => toggle(row)} className="font-bold text-amber-700 disabled:opacity-40">{row.isActive === false ? 'Enable' : 'Deactivate'}</button><button disabled={row.id === currentUserId} onClick={() => resetPassword(row)} className="inline-flex items-center font-bold text-sky-700 disabled:opacity-40"><KeyRound size={15} className="mr-1" />Reset password</button><button disabled={row.id === currentUserId} onClick={() => remove(row)} className="inline-flex items-center font-bold text-red-700 disabled:opacity-40"><Trash2 size={15} className="mr-1" />Delete</button><button disabled={row.id === currentUserId} onClick={() => purge(row)} className="font-bold text-red-900 underline disabled:opacity-40">Purge test data</button></div></td></tr>)}</tbody></table>{!visible.length && <p className="p-6 text-gray-500">No profiles found.</p>}</div>
  </main>;
}
