'use client';
import React from 'react';
import { Department, FreeCamp } from '@/types';
import { createFreeCamp, listDepartments, listFreeCamps } from '@/services/clinicService';

export default function AdminCamps(){
 const [departments,setDepartments]=React.useState<Department[]>([]); const [camps,setCamps]=React.useState<FreeCamp[]>([]);
 const [form,setForm]=React.useState({name:'',date:'',location:'Bhaktivedanta Health Care Center',capacity:'',departmentIds:[] as string[]}); const [message,setMessage]=React.useState('');
 const load=()=>Promise.all([listDepartments(),listFreeCamps()]).then(([d,c])=>{setDepartments(d);setCamps(c)});
 React.useEffect(()=>{load().catch(()=>setMessage('Unable to load camps.'));},[]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setMessage('');try{await createFreeCamp({...form,capacity:form.capacity?Number(form.capacity):undefined});await load();setForm({name:'',date:'',location:'Bhaktivedanta Health Care Center',capacity:'',departmentIds:[]});setMessage('Free camp created. It is now available at the counter.');}catch(error:any){setMessage(error?.message||'Could not create camp.')}};
 return <div className="mx-auto max-w-7xl px-4 py-12"><h1 className="text-3xl font-black">Free Camps</h1><p className="mb-8 text-gray-500">Create counter-only registration camps and select participating departments.</p><div className="grid gap-8 lg:grid-cols-2"><form onSubmit={submit} className="space-y-4 rounded-3xl border bg-white p-7"><input required placeholder="Camp name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="w-full rounded-xl border p-3"/><input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className="w-full rounded-xl border p-3"/><input required placeholder="Location" value={form.location} onChange={e=>setForm({...form,location:e.target.value})} className="w-full rounded-xl border p-3"/><input type="number" min="1" placeholder="Capacity (optional)" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})} className="w-full rounded-xl border p-3"/><fieldset><legend className="mb-2 font-bold">Departments</legend>{departments.map(d=><label key={d.id} className="mb-2 flex gap-2"><input type="checkbox" checked={form.departmentIds.includes(d.id)} onChange={e=>setForm({...form,departmentIds:e.target.checked?[...form.departmentIds,d.id]:form.departmentIds.filter(id=>id!==d.id)})}/>{d.name}</label>)}</fieldset>{message&&<p className="rounded-xl bg-sky-50 p-3 text-sm">{message}</p>}<button className="w-full rounded-xl bg-sky-600 py-3 font-bold text-white">Create free camp</button></form><div className="space-y-3">{camps.map(c=><div key={c.id} className="rounded-2xl border bg-white p-5"><h2 className="font-bold">{c.name}</h2><p className="text-sm text-gray-500">{c.date} · {c.location}</p><p className="text-sm">{c.registrationCount}{c.capacity?` / ${c.capacity}`:''} registrations · {c.departments.map(d=>d.name).join(', ')}</p></div>)}</div></div></div>;
}
