import React from 'react';
import Link from 'next/link';
import { FreeCamp, LabRegistration, PatientLookupResult, User } from '../../types';
import { PlusCircle, Printer, Search, Users } from 'lucide-react';
import { createRegistration, listFreeCamps, listRegistrations, lookupPatientsByPhone, recordReceiptPrint } from '../../services/clinicService';

const emptyForm = { name: '', phoneNo: '', address: '', departmentId: '', campId: '', roomId: '', existingPatientId: '', createSeparatePatient: false, isFreeCamp: true };

const CounterDashboard: React.FC<{ user: User }> = () => {
 const [registrations,setRegistrations]=React.useState<LabRegistration[]>([]); const [camps,setCamps]=React.useState<FreeCamp[]>([]);
 const [matches,setMatches]=React.useState<PatientLookupResult[]>([]); const [form,setForm]=React.useState(emptyForm);
 const [receipt,setReceipt]=React.useState<LabRegistration|null>(null); const [message,setMessage]=React.useState(''); const [saving,setSaving]=React.useState(false);
 const load=()=>Promise.all([listRegistrations(),listFreeCamps()]).then(([rows,campRows])=>{setRegistrations(rows);setCamps(campRows.filter(c=>c.isActive&&c.status==='OPEN'))});
 React.useEffect(()=>{load().catch(()=>setMessage('Unable to load counter registration data.'));},[]);
 const camp=camps.find(c=>c.id===form.campId); const departmentIds=[...new Set((camp?.rooms||[]).filter(r=>r.isActive).map(r=>r.departmentId))];
 const departments=departmentIds.map(id=>({id,name:camp?.rooms.find(r=>r.departmentId===id)?.departmentName||''}));
 const rooms=(camp?.rooms||[]).filter(r=>r.isActive&&r.departmentId===form.departmentId&&(!r.capacity||r.registrationCount<r.capacity));
 const lookup=async()=>{setMessage('');setMatches([]);if(form.phoneNo.length!==10)return;try{const rows=await lookupPatientsByPhone(form.phoneNo);setMatches(rows);if(rows.length===1&&rows[0].name.trim().toLowerCase()===form.name.trim().toLowerCase())setForm(current=>({...current,existingPatientId:rows[0].userId}));}catch(error:any){setMessage(error?.message||'Patient lookup failed.')}};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setMessage('');try{const row=await createRegistration(form);setRegistrations(previous=>[row,...previous]);setReceipt(row);setForm(emptyForm);setMatches([]);setMessage(`Registered successfully with patient ID ${row.patientId}.`);}catch(error:any){setMessage(error?.message||'Registration failed.')}finally{setSaving(false)}};
 const printReceipt=async()=>{if(!receipt)return;await recordReceiptPrint(receipt.id);window.print();};
 return <><div className="no-print mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="mb-8 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-extrabold">Camp Patient Registration</h1><p className="text-gray-500">Select an admin-created camp and configured department room.</p></div><Link href="/dashboard/payroll" className="rounded-xl bg-sky-50 px-4 py-3 font-bold text-sky-700">My Payroll</Link></div>
 <div className="grid gap-8 lg:grid-cols-[430px_1fr]"><form onSubmit={submit} className="space-y-4 rounded-3xl border bg-white p-7"><h2 className="flex items-center text-xl font-bold"><PlusCircle className="mr-2 text-sky-600"/>Register patient</h2><select required value={form.campId} onChange={e=>setForm({...form,campId:e.target.value,departmentId:'',roomId:''})} className="w-full rounded-xl border p-3"><option value="">Select open camp</option>{camps.map(c=><option key={c.id} value={c.id}>{c.name} — {c.date}</option>)}</select><input required placeholder="Patient name" value={form.name} onChange={e=>setForm({...form,name:e.target.value,existingPatientId:'',createSeparatePatient:false})} className="w-full rounded-xl border p-3"/><div className="flex gap-2"><input required inputMode="numeric" pattern="[0-9]{10}" placeholder="10-digit mobile number" value={form.phoneNo} onChange={e=>setForm({...form,phoneNo:e.target.value.replace(/\D/g,'').slice(0,10),existingPatientId:'',createSeparatePatient:false})} onBlur={lookup} className="min-w-0 flex-1 rounded-xl border p-3"/><button type="button" onClick={lookup} className="rounded-xl border px-3" aria-label="Find existing patient"><Search/></button></div>
 {matches.length>0&&<fieldset className="rounded-xl border border-amber-200 bg-amber-50 p-3"><legend className="font-bold">Confirm patient identity</legend>{matches.map(row=><label key={row.userId} className="mt-2 flex gap-2"><input required type="radio" name="existingPatient" checked={form.existingPatientId===row.userId&&!form.createSeparatePatient} onChange={()=>setForm({...form,existingPatientId:row.userId,createSeparatePatient:false,name:row.name,address:row.address||form.address})}/><span>{row.name} — {row.patientId}</span></label>)}<label className="mt-2 flex gap-2"><input required type="radio" name="existingPatient" checked={form.createSeparatePatient} onChange={()=>setForm({...form,existingPatientId:'',createSeparatePatient:true})}/><span>Different patient sharing this mobile number — create a new BHCC ID</span></label></fieldset>}
 <textarea required placeholder="Patient address" value={form.address} onChange={e=>setForm({...form,address:e.target.value})} className="w-full rounded-xl border p-3"/><select required value={form.departmentId} onChange={e=>setForm({...form,departmentId:e.target.value,roomId:''})} className="w-full rounded-xl border p-3"><option value="">Select department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><select value={form.roomId} onChange={e=>setForm({...form,roomId:e.target.value})} className="w-full rounded-xl border p-3"><option value="">Assign least-busy available room automatically</option>{rooms.map(r=><option key={r.id} value={r.id}>Room {r.roomNumber} ({r.registrationCount}{r.capacity?`/${r.capacity}`:''})</option>)}</select>{message&&<p className="rounded-xl bg-sky-50 p-3 text-sm text-sky-800">{message}</p>}<button disabled={saving} className="w-full rounded-xl bg-sky-600 py-4 font-bold text-white disabled:opacity-60">{saving?'Registering...':'Register and prepare receipt'}</button></form>
 <div className="overflow-hidden rounded-3xl border bg-white"><div className="flex items-center gap-3 border-b p-6"><Users className="text-sky-600"/><h2 className="font-bold">Recent camp registrations</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50"><tr><th className="p-4">Patient</th><th className="p-4">ID</th><th className="p-4">Department</th><th className="p-4">Room</th><th className="p-4">Token</th><th className="p-4"></th></tr></thead><tbody>{registrations.filter(r=>r.isFreeCamp).map(row=><tr key={row.id} className="border-t"><td className="p-4 font-bold">{row.name}<small className="block font-normal">{row.phoneNo}</small></td><td className="p-4">{row.patientId}</td><td className="p-4">{row.departmentName}</td><td className="p-4">{row.roomNumber||'Legacy'}</td><td className="p-4 font-bold text-sky-700">{row.tokenNumber}</td><td className="p-4"><button onClick={()=>setReceipt(row)} className="font-bold text-sky-700">Receipt</button></td></tr>)}</tbody></table></div></div></div>
 {receipt&&<div className="mt-6 rounded-3xl border bg-white p-6"><h2 className="text-xl font-bold">Receipt ready</h2><p>{receipt.name} · {receipt.departmentName} · Room {receipt.roomNumber}</p><button onClick={printReceipt} className="mt-4 flex items-center gap-2 rounded-xl bg-slate-900 px-5 py-3 font-bold text-white"><Printer/>Print receipt</button></div>}</div>
 {receipt&&<section className="print-only receipt-sheet"><h1>Bhaktivedanta Health Care Center</h1><h2>{receipt.campName}</h2><dl><dt>Patient name</dt><dd>{receipt.name}</dd><dt>Mobile number</dt><dd>{receipt.phoneNo}</dd><dt>Patient ID</dt><dd>{receipt.patientId}</dd><dt>Department</dt><dd>{receipt.departmentName}</dd><dt>Room number</dt><dd>{receipt.roomNumber}</dd><dt>Department token</dt><dd>{receipt.tokenNumber}</dd></dl></section>}</>;
};
export default CounterDashboard;
