'use client';
import React from 'react';
import { Appointment, Prescription, PrescriptionMedicine, User, UserRole } from '@/types';
import { listDoctorAppointments } from '@/services/clinicService';
import { amendPrescription, downloadPrescriptionPdf, finalizePrescription, getAppointmentPrescription, listPrescriptions, saveAppointmentPrescription } from '@/services/clinicalService';

const blankMedicine = (): PrescriptionMedicine => ({name:'',strength:'',dosageForm:'',dose:'',frequency:'',duration:'',foodInstructions:'',notes:''});
export default function PrescriptionDashboard({user}:{user:User}){
 const doctor=user.role===UserRole.DOCTOR; const admin=user.role===UserRole.ADMIN;
 const [appointments,setAppointments]=React.useState<Appointment[]>([]),[records,setRecords]=React.useState<Prescription[]>([]),[selected,setSelected]=React.useState('');
 const [draft,setDraft]=React.useState<Partial<Prescription>>({medicines:[blankMedicine()],tests:[]}); const [message,setMessage]=React.useState('');
 const loadRecords=React.useCallback(()=>listPrescriptions().then(setRecords),[]);
 React.useEffect(()=>{loadRecords().catch(()=>setRecords([]));if(doctor)listDoctorAppointments(user.id).then(setAppointments).catch(()=>setAppointments([]));},[doctor,user.id,loadRecords]);
 const choose=async(id:string)=>{setSelected(id);const row=await getAppointmentPrescription(id);setDraft({...row,medicines:row.medicines?.length?row.medicines:[blankMedicine()],tests:row.tests||[]});};
 const save=async()=>{try{const row=await saveAppointmentPrescription(selected,draft);setDraft(row);setMessage('Draft saved.');}catch(e){setMessage(e instanceof Error?e.message:'Could not save prescription.');}};
 const finalize=async()=>{if(!draft.id)return setMessage('Save the draft before finalizing.');try{await finalizePrescription(draft.id);setMessage('Prescription finalized and the patient was notified.');setSelected('');await loadRecords();}catch(e){setMessage(e instanceof Error?e.message:'Could not finalize prescription.');}};
 const updateMed=(index:number,key:keyof PrescriptionMedicine,value:string)=>setDraft({...draft,medicines:(draft.medicines||[]).map((m,i)=>i===index?{...m,[key]:value}:m)});
 return <main className="max-w-7xl mx-auto px-4 py-10 space-y-8"><div><h1 className="text-3xl font-black">E-Prescriptions</h1><p className="text-gray-500">{doctor?'Create, finalize and amend prescriptions for your own consultations.':admin?'Read-only administrative review of finalized clinic prescriptions.':'View and securely download prescriptions issued to you.'}</p></div>{message&&<p className="bg-sky-50 text-sky-800 rounded-xl p-4">{message}</p>}
 {doctor&&<section className="bg-white border rounded-3xl p-6 space-y-4"><h2 className="text-xl font-black">Consultation prescription</h2><select value={selected} onChange={(e)=>choose(e.target.value).catch((x)=>setMessage(x.message))} className="w-full border rounded-xl p-3"><option value="">Select appointment</option>{appointments.map(a=><option key={a.id} value={a.id}>{a.date} {a.time} — {a.patientName} ({a.department})</option>)}</select>{selected&&<><div className="grid md:grid-cols-2 gap-3">{(['symptoms','observations','diagnosis','advice'] as const).map(k=><textarea key={k} value={(draft[k] as string)||''} onChange={e=>setDraft({...draft,[k]:e.target.value})} placeholder={k[0].toUpperCase()+k.slice(1)} className="border rounded-xl p-3"/>)}<label className="text-sm font-bold">Follow-up date<input type="date" value={draft.followUpDate||''} onChange={e=>setDraft({...draft,followUpDate:e.target.value})} className="block w-full border rounded-xl p-3 mt-1"/></label></div><h3 className="font-black">Medicines</h3>{(draft.medicines||[]).map((m,i)=><div key={i} className="grid md:grid-cols-4 gap-2 border rounded-xl p-3">{(['name','strength','dosageForm','dose','frequency','duration','foodInstructions','notes'] as const).map(k=><input key={k} value={m[k]} onChange={e=>updateMed(i,k,e.target.value)} placeholder={k} className="border rounded-lg p-2"/>)}</div>)}<button onClick={()=>setDraft({...draft,medicines:[...(draft.medicines||[]),blankMedicine()]})} className="text-sky-700 font-bold">+ Add medicine</button><h3 className="font-black">Tests</h3>{(draft.tests||[]).map((t,i)=><div key={i} className="flex gap-2"><input value={t.name} onChange={e=>setDraft({...draft,tests:(draft.tests||[]).map((x,j)=>j===i?{...x,name:e.target.value}:x)})} placeholder="Test" className="border rounded-lg p-2 flex-1"/><input value={t.instructions} onChange={e=>setDraft({...draft,tests:(draft.tests||[]).map((x,j)=>j===i?{...x,instructions:e.target.value}:x)})} placeholder="Instructions" className="border rounded-lg p-2 flex-1"/></div>)}<button onClick={()=>setDraft({...draft,tests:[...(draft.tests||[]),{name:'',instructions:''}]})} className="text-sky-700 font-bold">+ Add test</button><div className="flex gap-3"><button onClick={save} className="bg-gray-900 text-white px-5 py-3 rounded-xl font-bold">Save draft</button><button onClick={finalize} className="bg-green-600 text-white px-5 py-3 rounded-xl font-bold">Finalize & notify patient</button></div></>}</section>}
 <section className="space-y-3"><h2 className="text-xl font-black">Finalized prescriptions</h2>{records.map(r=><article key={r.id} className="bg-white border rounded-2xl p-5 flex flex-wrap justify-between gap-4"><div><b>{r.prescriptionNumber}</b><p className="text-gray-500">{r.appointmentDate} — {doctor?r.patient.name:`Dr. ${r.doctor.name}`} — {r.diagnosis}</p></div><div className="flex gap-3"><button onClick={()=>downloadPrescriptionPdf(r.id,`${r.prescriptionNumber}.pdf`).catch(e=>setMessage(e.message))} className="text-sky-700 font-bold">Download PDF</button>{doctor&&<button onClick={async()=>{const next=await amendPrescription(r.id);setSelected(next.appointmentId);setDraft(next);setMessage('Amendment draft created.');}} className="text-amber-700 font-bold">Amend</button>}</div></article>)}{!records.length&&<p className="text-gray-500">No finalized prescriptions yet.</p>}</section></main>;
}
