# Generated by Django 5.2.17 on 2026-08-23 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('LEADER', 'Group leader'), ('ADMIN', 'Group administrator')], default='MEMBER', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_group_memberships', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='reporting.servicegroup')),
            ],
            options={
                'ordering': ['group__name', 'user__first_name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='reporting.servicegroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporting_periods', to='reporting.servicegroup')),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CARRIED_FORWARD', 'Carried forward'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('result', models.TextField(blank=True, default='')),
                ('evidence_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carried_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carry_forwards', to='reporting.servicetask')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='reporting.servicecategory')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborative_tasks', to='reporting.groupmembership')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_tasks', to='reporting.groupmembership')),
            ],
            options={
                'ordering': ['deadline', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_updates', to='reporting.groupmembership')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reporting.servicetask')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happiness', models.TextField(blank=True, default='')),
                ('challenges', models.TextField(blank=True, default='')),
                ('needs_support', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REOPENED', 'Reopened')], default='DRAFT', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_reports', to='reporting.groupmembership')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reporting.reportingperiod')),
            ],
            options={
                'ordering': ['-period__week_start', 'membership__user__first_name'],
            },
        ),
        migrations.AddField(
            model_name='servicetask',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='reporting.weeklyservicereport'),
        ),
        migrations.CreateModel(
            name='ReportRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_revisions', to='reporting.groupmembership')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='reporting.weeklyservicereport')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_given', to='reporting.groupmembership')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leader_feedback', to='reporting.weeklyservicereport')),
            ],
        ),
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('contribution', models.CharField(blank=True, default='', max_length=180)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appreciations_received', to='reporting.groupmembership')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations', to='reporting.weeklyservicereport')),
            ],
        ),
        migrations.AddConstraint(
            model_name='servicecategory',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_group_service_category'),
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.UniqueConstraint(fields=('group', 'week_start'), name='unique_group_reporting_week'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_service_group_membership'),
        ),
        migrations.AddConstraint(
            model_name='weeklyservicereport',
            constraint=models.UniqueConstraint(fields=('period', 'membership'), name='one_weekly_report_per_member'),
        ),
        migrations.AddConstraint(
            model_name='reportrevision',
            constraint=models.UniqueConstraint(fields=('report', 'revision'), name='unique_weekly_report_revision'),
        ),
        migrations.AddConstraint(
            model_name='appreciation',
            constraint=models.UniqueConstraint(fields=('report', 'recipient'), name='one_appreciation_per_report_recipient'),
        ),
    ]
