'use client';
import React from 'react';
import Link from 'next/link';
import { listDepartments, listDoctors } from '@/services/clinicService';
import { Department, User } from '@/types';

export default function PricingPage(){
 const [departments,setDepartments]=React.useState<Department[]>([]),[doctors,setDoctors]=React.useState<User[]>([]),[error,setError]=React.useState('');
 React.useEffect(()=>{Promise.all([listDepartments(),listDoctors()]).then(([d,u])=>{setDepartments(d);setDoctors(u);}).catch(()=>setError('Pricing could not be loaded. Please contact the clinic.'));},[]);
 return <main className="bg-white"><section className="bg-sky-950 px-6 py-16 text-white"><div className="mx-auto max-w-5xl"><p className="text-sm font-black uppercase tracking-[.2em] text-sky-300">Transparent charges</p><h1 className="mt-3 text-4xl font-black md:text-5xl">Consultation Pricing</h1><p className="mt-5 text-lg text-sky-100">Current consultation fees are maintained by the clinic and loaded directly from our booking system.</p><p className="mt-4 text-sm text-sky-300">Effective 25 August 2026 · Last updated 25 August 2026</p></div></section><section className="mx-auto max-w-5xl space-y-8 px-6 py-14">{error&&<p className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<div className="grid gap-4 md:grid-cols-2">{departments.map(department=><article key={department.id} className="rounded-2xl border p-5"><h2 className="text-xl font-black">{department.name}</h2><p className="mt-2 text-gray-600">{department.description}</p><p className="mt-4 text-2xl font-black text-sky-700">Base fee: ₹{department.baseFee.toLocaleString('en-IN')}</p><div className="mt-4 space-y-2">{doctors.filter(x=>x.department===department.name).map(doctor=><div key={doctor.id} className="flex justify-between border-t pt-2"><span>{doctor.name}</span><b>{typeof doctor.fee==='number'?`₹${doctor.fee.toLocaleString('en-IN')}`:'Confirm with clinic'}</b></div>)}</div></article>)}</div>{!departments.length&&!error&&<p>Loading current consultation fees…</p>}<div className="rounded-2xl bg-sky-50 p-6"><h2 className="text-xl font-black">Payment charges</h2><p className="mt-2">Online checkout currently adds a 2% payment-gateway charge, rounded up to the nearest rupee. The complete payable amount is displayed before you approve payment. Pay-at-counter appointments do not include this online gateway charge.</p></div><div><h2 className="text-xl font-black">Important information</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-gray-700"><li>Fees may vary by doctor and service and may be updated prospectively by the clinic.</li><li>Investigations, medicines, procedures and services outside the selected consultation are not included unless explicitly shown.</li><li>The amount displayed at checkout is the amount applicable to that booking.</li></ul><Link href="/book" className="mt-6 inline-block rounded-xl bg-sky-600 px-5 py-3 font-bold text-white">Book an appointment</Link></div></section></main>;
}
