'use client';

import React from 'react';
import { addReportFeedback, AppreciationDraft, getCurrentReport, getGroupManagement, getGroupReports, getReportingAccess, GroupManagement, GroupReportSummary, reopenWeeklyReport, ReportingMembership, saveWeeklyReport, ServiceTaskDraft, submitWeeklyReport, updateGroupManagement, WeeklyReport } from '@/services/reportingService';

const blankTask=():ServiceTaskDraft=>({title:'',description:'',priority:'MEDIUM',status:'NOT_STARTED',result:'',evidenceUrl:'',collaboratorIds:[]});
const blankAppreciation=():AppreciationDraft=>({recipientId:'',reason:'',contribution:''});

export default function ServiceReportingPortal(){
 const [memberships,setMemberships]=React.useState<ReportingMembership[]>([]),[selected,setSelected]=React.useState('');
 const [report,setReport]=React.useState<WeeklyReport|null>(null),[summary,setSummary]=React.useState<GroupReportSummary|null>(null);
 const [management,setManagement]=React.useState<GroupManagement|null>(null);
 const [message,setMessage]=React.useState(''),[loading,setLoading]=React.useState(true),[mode,setMode]=React.useState<'report'|'group'|'manage'>('report');
 const membership=memberships.find(x=>x.id===selected),canReview=membership?.role==='LEADER'||membership?.role==='ADMIN';
 React.useEffect(()=>{getReportingAccess().then(data=>{setMemberships(data.memberships);setSelected(data.memberships[0]?.id||'');}).catch(e=>setMessage(e.message)).finally(()=>setLoading(false));},[]);
 React.useEffect(()=>{if(!selected)return;setLoading(true);Promise.all([getCurrentReport(selected),canReview?getGroupReports(selected):Promise.resolve(null),membership?.role==='ADMIN'?getGroupManagement(selected):Promise.resolve(null)]).then(([own,group,manage])=>{setReport(own);setSummary(group);setManagement(manage);}).catch(e=>setMessage(e.message)).finally(()=>setLoading(false));},[selected,canReview,membership?.role]);
 const updateTask=(index:number,patch:Partial<ServiceTaskDraft>)=>report&&setReport({...report,tasks:report.tasks.map((x,i)=>i===index?{...x,...patch}:x)});
 const updateApp=(index:number,patch:Partial<AppreciationDraft>)=>report&&setReport({...report,appreciations:report.appreciations.map((x,i)=>i===index?{...x,...patch}:x)});
 const save=async()=>{if(!report)return;try{setReport(await saveWeeklyReport(report));setMessage('Draft saved with revision history.');}catch(e){setMessage(e instanceof Error?e.message:'Could not save report.');}};
 const submit=async()=>{if(!report||!confirm('Submit this weekly report? It will be locked until a group leader reopens it.'))return;try{setReport(await submitWeeklyReport(report.id));setMessage('Weekly report submitted.');}catch(e){setMessage(e instanceof Error?e.message:'Could not submit report.');}};
 if(loading&&!memberships.length)return <main className="mx-auto max-w-7xl p-6 lg:p-12"><p>Loading service reporting…</p></main>;
 if(!memberships.length)return <main className="mx-auto max-w-3xl p-6 lg:p-12"><h1 className="text-3xl font-black">Weekly Service & Reflection</h1><div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-900">Your login does not have an active group membership. A group administrator must add your existing account before you can access reports.</div></main>;
 return <main className="mx-auto max-w-7xl space-y-6 p-4 py-10 lg:p-12">
  <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-bold uppercase tracking-widest text-sky-600">Group management</p><h1 className="text-3xl font-black">Weekly Service & Reflection</h1><p className="text-gray-500">Isolated from clinic, patient and prescription records.</p></div><select value={selected} onChange={e=>setSelected(e.target.value)} className="rounded-xl border bg-white p-3">{memberships.map(x=><option key={x.id} value={x.id}>{x.groupName} — {x.role}</option>)}</select></header>
  {message&&<p className="rounded-xl bg-sky-50 p-4 text-sky-900">{message}</p>}
  {canReview&&<div className="flex flex-wrap gap-2"><button onClick={()=>setMode('report')} className={`rounded-xl px-4 py-2 font-bold ${mode==='report'?'bg-sky-600 text-white':'bg-white border'}`}>My report</button><button onClick={()=>setMode('group')} className={`rounded-xl px-4 py-2 font-bold ${mode==='group'?'bg-sky-600 text-white':'bg-white border'}`}>Group review</button>{membership?.role==='ADMIN'&&<button onClick={()=>setMode('manage')} className={`rounded-xl px-4 py-2 font-bold ${mode==='manage'?'bg-sky-600 text-white':'bg-white border'}`}>Group setup</button>}</div>}
  {mode==='report'&&report&&<section className="space-y-6">
   <div className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-2"><h2 className="text-xl font-black">{report.weekStart} to {report.weekEnd}</h2><span className="rounded-full bg-gray-100 px-3 py-1 font-bold">{report.status}</span></div><p className="text-sm text-gray-500">Deadline: {new Date(report.deadline).toLocaleString()}</p></div>
   <div className="grid gap-4 md:grid-cols-2"><label className="font-bold">What made you happy this week?<textarea disabled={report.status==='SUBMITTED'} value={report.happiness} onChange={e=>setReport({...report,happiness:e.target.value})} className="mt-2 min-h-32 w-full rounded-xl border p-3 font-normal"/></label><label className="font-bold">Challenges or concerns<textarea disabled={report.status==='SUBMITTED'} value={report.challenges} onChange={e=>setReport({...report,challenges:e.target.value})} className="mt-2 min-h-32 w-full rounded-xl border p-3 font-normal"/></label></div>
   <label className="flex gap-2 font-bold"><input disabled={report.status==='SUBMITTED'} type="checkbox" checked={report.needsSupport} onChange={e=>setReport({...report,needsSupport:e.target.checked})}/>I need support from my group leader.</label>
   <div className="rounded-2xl border bg-white p-5 space-y-3"><h2 className="text-xl font-black">Appreciations</h2>{report.appreciations.map((a,i)=><div key={i} className="grid gap-2 md:grid-cols-3"><select disabled={report.status==='SUBMITTED'} value={a.recipientId} onChange={e=>updateApp(i,{recipientId:e.target.value})} className="rounded-xl border p-3"><option value="">Select member</option>{report.members?.filter(x=>x.id!==report.membership.id).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input disabled={report.status==='SUBMITTED'} value={a.reason} onChange={e=>updateApp(i,{reason:e.target.value})} placeholder="Reason for appreciation" className="rounded-xl border p-3"/><input disabled={report.status==='SUBMITTED'} value={a.contribution} onChange={e=>updateApp(i,{contribution:e.target.value})} placeholder="Related contribution" className="rounded-xl border p-3"/></div>)}{report.status!=='SUBMITTED'&&<button onClick={()=>setReport({...report,appreciations:[...report.appreciations,blankAppreciation()]})} className="font-bold text-sky-700">+ Add appreciation</button>}</div>
   <div className="rounded-2xl border bg-white p-5 space-y-4"><h2 className="text-xl font-black">Service plans and progress</h2>{report.tasks.map((task,i)=><div key={task.id||i} className="grid gap-2 rounded-xl border p-4 md:grid-cols-3"><input disabled={report.status==='SUBMITTED'} value={task.title} onChange={e=>updateTask(i,{title:e.target.value})} placeholder="Service/task title" className="rounded-lg border p-2"/><select disabled={report.status==='SUBMITTED'} value={task.categoryId||''} onChange={e=>updateTask(i,{categoryId:e.target.value||null})} className="rounded-lg border p-2"><option value="">No category</option>{report.categories?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select disabled={report.status==='SUBMITTED'} value={task.status} onChange={e=>updateTask(i,{status:e.target.value as ServiceTaskDraft['status']})} className="rounded-lg border p-2">{['NOT_STARTED','IN_PROGRESS','COMPLETED','CARRIED_FORWARD','CANCELLED'].map(x=><option key={x}>{x.replaceAll('_',' ')}</option>)}</select><textarea disabled={report.status==='SUBMITTED'} value={task.description} onChange={e=>updateTask(i,{description:e.target.value})} placeholder="Description" className="rounded-lg border p-2"/><label className="text-sm font-bold">Deadline<input disabled={report.status==='SUBMITTED'} type="date" value={task.deadline||''} onChange={e=>updateTask(i,{deadline:e.target.value||null})} className="mt-1 block w-full rounded-lg border p-2 font-normal"/></label><input disabled={report.status==='SUBMITTED'} value={task.result} onChange={e=>updateTask(i,{result:e.target.value})} placeholder="Result or update" className="rounded-lg border p-2"/></div>)}{report.status!=='SUBMITTED'&&<button onClick={()=>setReport({...report,tasks:[...report.tasks,blankTask()]})} className="font-bold text-sky-700">+ Add service task</button>}</div>
   {report.feedback.length>0&&<div className="rounded-2xl border bg-white p-5"><h2 className="font-black">Leader feedback</h2>{report.feedback.map((x,i)=><blockquote key={i} className="mt-3 border-l-4 border-sky-500 pl-3"><p>{x.comment}</p><small>{x.leaderName} · {new Date(x.createdAt).toLocaleString()}</small></blockquote>)}</div>}
   {report.status!=='SUBMITTED'&&<div className="flex gap-3"><button onClick={save} className="rounded-xl bg-gray-900 px-5 py-3 font-bold text-white">Save draft</button><button onClick={submit} className="rounded-xl bg-green-600 px-5 py-3 font-bold text-white">Submit report</button></div>}
  </section>}
  {mode==='group'&&summary&&<section className="space-y-5"><div className="grid gap-4 sm:grid-cols-3"><Metric label="Reports started" value={summary.reports.length}/><Metric label="Submitted" value={summary.reports.filter(x=>x.status==='SUBMITTED').length}/><Metric label="Pending members" value={summary.pendingMembers.length}/></div>{summary.pendingMembers.length>0&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-black">No report started</h2><p>{summary.pendingMembers.map(x=>x.name).join(', ')}</p></div>}<div className="space-y-3">{summary.reports.map(row=><article key={row.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-black">{row.membership.name}</h3><p className="text-gray-500">{row.status} · {row.tasks.filter(x=>x.status==='COMPLETED').length}/{row.tasks.length} tasks completed{row.needsSupport?' · Support requested':''}</p></div><div className="flex gap-2">{row.status==='SUBMITTED'&&<><button onClick={async()=>{const comment=prompt('Leader feedback');if(comment){await addReportFeedback(row.id,comment);setSummary(await getGroupReports(selected));}}} className="font-bold text-sky-700">Add feedback</button><button onClick={async()=>{if(confirm('Reopen this report for the member?')){await reopenWeeklyReport(row.id);setSummary(await getGroupReports(selected));}}} className="font-bold text-amber-700">Reopen</button></>}</div></div><p className="mt-3"><b>Happy:</b> {row.happiness||'—'}</p><p><b>Challenges:</b> {row.challenges||'—'}</p></article>)}</div></section>}
  {mode==='manage'&&management&&<GroupSetup management={management} membershipId={selected} onChange={setManagement} onMessage={setMessage}/>}
 </main>;
}

function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl bg-slate-900 p-5 text-white"><p className="text-sm text-slate-300">{label}</p><p className="text-3xl font-black">{value}</p></div>}

function GroupSetup({management,membershipId,onChange,onMessage}:{management:GroupManagement;membershipId:string;onChange:(x:GroupManagement)=>void;onMessage:(x:string)=>void}){
 const [email,setEmail]=React.useState(''),[role,setRole]=React.useState<'MEMBER'|'LEADER'|'ADMIN'>('MEMBER'),[category,setCategory]=React.useState('');
 const run=async(payload:Record<string,unknown>)=>{try{onChange(await updateGroupManagement(membershipId,payload));onMessage('Group setup updated.');}catch(e){onMessage(e instanceof Error?e.message:'Could not update group.');}};
 return <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-5 space-y-4"><h2 className="text-xl font-black">Members</h2><div className="flex flex-wrap gap-2"><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Existing BHCC account email" className="min-w-64 flex-1 rounded-xl border p-3"/><select value={role} onChange={e=>setRole(e.target.value as typeof role)} className="rounded-xl border p-3"><option>MEMBER</option><option>LEADER</option><option>ADMIN</option></select><button onClick={()=>run({action:'ADD_MEMBER',email,role}).then(()=>setEmail(''))} className="rounded-xl bg-sky-600 px-4 font-bold text-white">Add</button></div><p className="text-sm text-gray-500">Only existing logins can be enrolled; this flow never creates or changes clinical profiles.</p>{management.members.map(x=><div key={x.id} className="flex items-center justify-between border-t py-3"><div><b>{x.name}</b><p className="text-sm text-gray-500">{x.email} · {x.role}</p></div><button disabled={x.id===membershipId} onClick={()=>run({action:'UPDATE_MEMBER',memberId:x.id,isActive:!x.isActive})} className="font-bold text-amber-700 disabled:opacity-40">{x.isActive?'Deactivate':'Reactivate'}</button></div>)}</div><div className="rounded-2xl border bg-white p-5 space-y-4"><h2 className="text-xl font-black">Service categories</h2><div className="flex gap-2"><input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Category name" className="flex-1 rounded-xl border p-3"/><button onClick={()=>run({action:'ADD_CATEGORY',name:category}).then(()=>setCategory(''))} className="rounded-xl bg-sky-600 px-4 font-bold text-white">Add</button></div>{management.categories.map(x=><p key={x.id} className="border-t py-3 font-bold">{x.name}</p>)}</div></section>;
}
